language: node_js
node_js:
  - "4"
script:
  - npm run lint
  - npm test
after_success:
  - npm run coveralls
notifications:
  email: false
  slack:
    secure: V3v+RTLnSF0V1cXRvQTsluiBusOIp2pR/54uD6CjQhv16GCjd2iB7orhbCcynMeaDR5e1eiJLybCKGeXFcfg/M/cZUk+H93nIGvK2jzj0xHAEB6cCOjEAf3BCqD9F3kX/EnMO7TgXO+5ZNK7SvcUw7qhJhYcjPgjdP9ihIwXChU=
sudo: false
